FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    else echo "Lockfile not found." && exit 1; \
    fi

COPY . .

ARG REACT_APP_REPO_NAME

ENV REACT_APP_REPO_NAME=${REACT_APP_REPO_NAME}

RUN yarn build

RUN yarn global add serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
