version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.Motor
      args:
        REACT_APP_BUILD_TARGET: motor
    ports:
      - "3000:3000"

  app2:
    build:
      context: .
      dockerfile: Dockerfile.Navi
      args:
        REACT_APP_BUILD_TARGET: navi
    ports:
      - "3001:3001"
