name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 3000:3000
          - 3001:3001
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Motor app
        run: |
          docker-compose -f docker-compose.yml up --build -d app1
          docker-compose -f docker-compose.yml run --rm app1 yarn test

      - name: Build and run Navi app
        run: |
          docker-compose -f docker-compose.yml up --build -d app2
          docker-compose -f docker-compose.yml run --rm app2 yarn test
